# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Tue Nov  1 13:43:59 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1340, 924)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_main = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_tv = QtGui.QWidget()
        self.tab_tv.setObjectName("tab_tv")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_tv)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView_shows = QtGui.QListView(self.tab_tv)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_shows.sizePolicy().hasHeightForWidth())
        self.listView_shows.setSizePolicy(sizePolicy)
        self.listView_shows.setMinimumSize(QtCore.QSize(250, 0))
        self.listView_shows.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listView_shows.setObjectName("listView_shows")
        self.horizontalLayout.addWidget(self.listView_shows)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_tv_info = QtGui.QTabWidget(self.tab_tv)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_tv_info.sizePolicy().hasHeightForWidth())
        self.tabWidget_tv_info.setSizePolicy(sizePolicy)
        self.tabWidget_tv_info.setObjectName("tabWidget_tv_info")
        self.tab_series_info = QtGui.QWidget()
        self.tab_series_info.setObjectName("tab_series_info")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_series_info)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_series_name = QtGui.QLineEdit(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_series_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_series_name.setSizePolicy(sizePolicy)
        self.lineEdit_series_name.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_series_name.setObjectName("lineEdit_series_name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lineEdit_series_name)
        self.label_series_name = QtGui.QLabel(self.tab_series_info)
        self.label_series_name.setObjectName("label_series_name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_series_name)
        self.plainTextEdit_overview = QtGui.QPlainTextEdit(self.tab_series_info)
        self.plainTextEdit_overview.setMinimumSize(QtCore.QSize(300, 50))
        self.plainTextEdit_overview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit_overview.setObjectName("plainTextEdit_overview")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.plainTextEdit_overview)
        self.label_overview = QtGui.QLabel(self.tab_series_info)
        self.label_overview.setObjectName("label_overview")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_overview)
        self.lineEdit_network = QtGui.QLineEdit(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_network.sizePolicy().hasHeightForWidth())
        self.lineEdit_network.setSizePolicy(sizePolicy)
        self.lineEdit_network.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_network.setObjectName("lineEdit_network")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEdit_network)
        self.label_network = QtGui.QLabel(self.tab_series_info)
        self.label_network.setObjectName("label_network")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_network)
        self.lineEdit_airtime = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_airtime.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_airtime.setObjectName("lineEdit_airtime")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEdit_airtime)
        self.label_airtime = QtGui.QLabel(self.tab_series_info)
        self.label_airtime.setObjectName("label_airtime")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_airtime)
        self.lineEdit_runtime = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_runtime.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_runtime.setObjectName("lineEdit_runtime")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lineEdit_runtime)
        self.label_runtime = QtGui.QLabel(self.tab_series_info)
        self.label_runtime.setObjectName("label_runtime")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_runtime)
        self.lineEdit_status = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_status.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lineEdit_status)
        self.label_status = QtGui.QLabel(self.tab_series_info)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_status)
        self.lineEdit_tvdb_series_id = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_tvdb_series_id.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_tvdb_series_id.setObjectName("lineEdit_tvdb_series_id")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lineEdit_tvdb_series_id)
        self.label_tvdb_series_id = QtGui.QLabel(self.tab_series_info)
        self.label_tvdb_series_id.setObjectName("label_tvdb_series_id")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_tvdb_series_id)
        self.combo_actors = QtGui.QComboBox(self.tab_series_info)
        self.combo_actors.setMinimumSize(QtCore.QSize(300, 0))
        self.combo_actors.setObjectName("combo_actors")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.combo_actors)
        self.label_actors = QtGui.QLabel(self.tab_series_info)
        self.label_actors.setObjectName("label_actors")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_actors)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_save_series_changes = QtGui.QPushButton(self.tab_series_info)
        self.pushButton_save_series_changes.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_save_series_changes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_save_series_changes.setObjectName("pushButton_save_series_changes")
        self.gridLayout_4.addWidget(self.pushButton_save_series_changes, 0, 0, 1, 1)
        self.pushButton_revert_series_changes = QtGui.QPushButton(self.tab_series_info)
        self.pushButton_revert_series_changes.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_revert_series_changes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_revert_series_changes.setObjectName("pushButton_revert_series_changes")
        self.gridLayout_4.addWidget(self.pushButton_revert_series_changes, 1, 0, 1, 1)
        self.formLayout.setLayout(8, QtGui.QFormLayout.LabelRole, self.gridLayout_4)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.label_series_banner = QtGui.QLabel(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_series_banner.sizePolicy().hasHeightForWidth())
        self.label_series_banner.setSizePolicy(sizePolicy)
        self.label_series_banner.setMinimumSize(QtCore.QSize(300, 450))
        self.label_series_banner.setMaximumSize(QtCore.QSize(300, 450))
        self.label_series_banner.setObjectName("label_series_banner")
        self.horizontalLayout_2.addWidget(self.label_series_banner)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_banner_wide = QtGui.QLabel(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_banner_wide.sizePolicy().hasHeightForWidth())
        self.label_banner_wide.setSizePolicy(sizePolicy)
        self.label_banner_wide.setMinimumSize(QtCore.QSize(760, 140))
        self.label_banner_wide.setMaximumSize(QtCore.QSize(760, 140))
        self.label_banner_wide.setObjectName("label_banner_wide")
        self.horizontalLayout_6.addWidget(self.label_banner_wide)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.pushButton_new_series_poster = QtGui.QPushButton(self.tab_series_info)
        self.pushButton_new_series_poster.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_series_poster.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_series_poster.setObjectName("pushButton_new_series_poster")
        self.verticalLayout_7.addWidget(self.pushButton_new_series_poster)
        self.pushButton_new_series_wide_banner = QtGui.QPushButton(self.tab_series_info)
        self.pushButton_new_series_wide_banner.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_series_wide_banner.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_series_wide_banner.setObjectName("pushButton_new_series_wide_banner")
        self.verticalLayout_7.addWidget(self.pushButton_new_series_wide_banner)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.tabWidget_tv_info.addTab(self.tab_series_info, "")
        self.tab_season_info = QtGui.QWidget()
        self.tab_season_info.setObjectName("tab_season_info")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_season_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listView_season_episode_full = QtGui.QListView(self.tab_season_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_season_episode_full.sizePolicy().hasHeightForWidth())
        self.listView_season_episode_full.setSizePolicy(sizePolicy)
        self.listView_season_episode_full.setMinimumSize(QtCore.QSize(300, 0))
        self.listView_season_episode_full.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listView_season_episode_full.setObjectName("listView_season_episode_full")
        self.horizontalLayout_4.addWidget(self.listView_season_episode_full)
        self.label_season_poster = QtGui.QLabel(self.tab_season_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_season_poster.sizePolicy().hasHeightForWidth())
        self.label_season_poster.setSizePolicy(sizePolicy)
        self.label_season_poster.setMinimumSize(QtCore.QSize(300, 450))
        self.label_season_poster.setMaximumSize(QtCore.QSize(300, 450))
        self.label_season_poster.setObjectName("label_season_poster")
        self.horizontalLayout_4.addWidget(self.label_season_poster)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_season_banner_wide = QtGui.QLabel(self.tab_season_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_season_banner_wide.sizePolicy().hasHeightForWidth())
        self.label_season_banner_wide.setSizePolicy(sizePolicy)
        self.label_season_banner_wide.setMinimumSize(QtCore.QSize(760, 140))
        self.label_season_banner_wide.setMaximumSize(QtCore.QSize(760, 140))
        self.label_season_banner_wide.setObjectName("label_season_banner_wide")
        self.horizontalLayout_5.addWidget(self.label_season_banner_wide)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.pushButton_new_season_poster = QtGui.QPushButton(self.tab_season_info)
        self.pushButton_new_season_poster.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_season_poster.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_season_poster.setObjectName("pushButton_new_season_poster")
        self.verticalLayout_4.addWidget(self.pushButton_new_season_poster)
        self.pushButton_new_season_wide = QtGui.QPushButton(self.tab_season_info)
        self.pushButton_new_season_wide.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_season_wide.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_season_wide.setObjectName("pushButton_new_season_wide")
        self.verticalLayout_4.addWidget(self.pushButton_new_season_wide)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget_tv_info.addTab(self.tab_season_info, "")
        self.tab_episode_info = QtGui.QWidget()
        self.tab_episode_info.setObjectName("tab_episode_info")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_episode_info)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.line_episode_name = QtGui.QLineEdit(self.tab_episode_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_episode_name.sizePolicy().hasHeightForWidth())
        self.line_episode_name.setSizePolicy(sizePolicy)
        self.line_episode_name.setMinimumSize(QtCore.QSize(400, 0))
        self.line_episode_name.setObjectName("line_episode_name")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.line_episode_name)
        self.label_episode_name = QtGui.QLabel(self.tab_episode_info)
        self.label_episode_name.setObjectName("label_episode_name")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_episode_name)
        self.text_episode_plot = QtGui.QPlainTextEdit(self.tab_episode_info)
        self.text_episode_plot.setMinimumSize(QtCore.QSize(400, 100))
        self.text_episode_plot.setObjectName("text_episode_plot")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.text_episode_plot)
        self.label_plot = QtGui.QLabel(self.tab_episode_info)
        self.label_plot.setObjectName("label_plot")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_plot)
        self.line_airdate = QtGui.QLineEdit(self.tab_episode_info)
        self.line_airdate.setMinimumSize(QtCore.QSize(400, 0))
        self.line_airdate.setObjectName("line_airdate")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.line_airdate)
        self.label_airdate = QtGui.QLabel(self.tab_episode_info)
        self.label_airdate.setObjectName("label_airdate")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_airdate)
        self.line_tvdb_id = QtGui.QLineEdit(self.tab_episode_info)
        self.line_tvdb_id.setMinimumSize(QtCore.QSize(400, 0))
        self.line_tvdb_id.setObjectName("line_tvdb_id")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.line_tvdb_id)
        self.label_tvdb_id = QtGui.QLabel(self.tab_episode_info)
        self.label_tvdb_id.setObjectName("label_tvdb_id")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_tvdb_id)
        self.line_tvdb_rating = QtGui.QLineEdit(self.tab_episode_info)
        self.line_tvdb_rating.setMinimumSize(QtCore.QSize(400, 0))
        self.line_tvdb_rating.setObjectName("line_tvdb_rating")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.line_tvdb_rating)
        self.label_tvdb_rating = QtGui.QLabel(self.tab_episode_info)
        self.label_tvdb_rating.setObjectName("label_tvdb_rating")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_tvdb_rating)
        self.combo_writers = QtGui.QComboBox(self.tab_episode_info)
        self.combo_writers.setMinimumSize(QtCore.QSize(400, 0))
        self.combo_writers.setObjectName("combo_writers")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.combo_writers)
        self.label_writers = QtGui.QLabel(self.tab_episode_info)
        self.label_writers.setObjectName("label_writers")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_writers)
        self.combo_directors = QtGui.QComboBox(self.tab_episode_info)
        self.combo_directors.setMinimumSize(QtCore.QSize(400, 0))
        self.combo_directors.setObjectName("combo_directors")
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.combo_directors)
        self.label_director = QtGui.QLabel(self.tab_episode_info)
        self.label_director.setObjectName("label_director")
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_director)
        self.combo_guests = QtGui.QComboBox(self.tab_episode_info)
        self.combo_guests.setMinimumSize(QtCore.QSize(400, 0))
        self.combo_guests.setObjectName("combo_guests")
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.combo_guests)
        self.label_guests = QtGui.QLabel(self.tab_episode_info)
        self.label_guests.setObjectName("label_guests")
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.label_guests)
        self.pushButton_save_episode_changes = QtGui.QPushButton(self.tab_episode_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_episode_changes.sizePolicy().hasHeightForWidth())
        self.pushButton_save_episode_changes.setSizePolicy(sizePolicy)
        self.pushButton_save_episode_changes.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_save_episode_changes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_save_episode_changes.setObjectName("pushButton_save_episode_changes")
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.pushButton_save_episode_changes)
        self.pushButton_revert_episode_changes = QtGui.QPushButton(self.tab_episode_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_revert_episode_changes.sizePolicy().hasHeightForWidth())
        self.pushButton_revert_episode_changes.setSizePolicy(sizePolicy)
        self.pushButton_revert_episode_changes.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_revert_episode_changes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_revert_episode_changes.setObjectName("pushButton_revert_episode_changes")
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.pushButton_revert_episode_changes)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_episode_thumb = QtGui.QLabel(self.tab_episode_info)
        self.label_episode_thumb.setMinimumSize(QtCore.QSize(400, 225))
        self.label_episode_thumb.setMaximumSize(QtCore.QSize(400, 225))
        self.label_episode_thumb.setObjectName("label_episode_thumb")
        self.verticalLayout_3.addWidget(self.label_episode_thumb)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.tabWidget_tv_info.addTab(self.tab_episode_info, "")
        self.verticalLayout.addWidget(self.tabWidget_tv_info)
        self.columnView_season_episode = QtGui.QColumnView(self.tab_tv)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columnView_season_episode.sizePolicy().hasHeightForWidth())
        self.columnView_season_episode.setSizePolicy(sizePolicy)
        self.columnView_season_episode.setMinimumSize(QtCore.QSize(0, 100))
        self.columnView_season_episode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.columnView_season_episode.setObjectName("columnView_season_episode")
        self.verticalLayout.addWidget(self.columnView_season_episode)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget_main.addTab(self.tab_tv, "")
        self.tab_movies = QtGui.QWidget()
        self.tab_movies.setObjectName("tab_movies")
        self.tabWidget_main.addTab(self.tab_movies, "")
        self.gridLayout.addWidget(self.tabWidget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1340, 22))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuSeries = QtGui.QMenu(self.menuSave)
        self.menuSeries.setObjectName("menuSeries")
        self.menuEpisode = QtGui.QMenu(self.menuSave)
        self.menuEpisode.setObjectName("menuEpisode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionScan_Files = QtGui.QAction(MainWindow)
        self.actionScan_Files.setObjectName("actionScan_Files")
        self.actionEdit_Preferences = QtGui.QAction(MainWindow)
        self.actionEdit_Preferences.setObjectName("actionEdit_Preferences")
        self.actionClear_Cache = QtGui.QAction(MainWindow)
        self.actionClear_Cache.setObjectName("actionClear_Cache")
        self.actionSave_Series_Artwork = QtGui.QAction(MainWindow)
        self.actionSave_Series_Artwork.setObjectName("actionSave_Series_Artwork")
        self.actionSave_Series_nfo_Files = QtGui.QAction(MainWindow)
        self.actionSave_Series_nfo_Files.setObjectName("actionSave_Series_nfo_Files")
        self.actionSelected_Series_nfo_Files = QtGui.QAction(MainWindow)
        self.actionSelected_Series_nfo_Files.setObjectName("actionSelected_Series_nfo_Files")
        self.actionSelected_Series_Artwork = QtGui.QAction(MainWindow)
        self.actionSelected_Series_Artwork.setObjectName("actionSelected_Series_Artwork")
        self.actionSave_all = QtGui.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionSave_series_artwork = QtGui.QAction(MainWindow)
        self.actionSave_series_artwork.setObjectName("actionSave_series_artwork")
        self.actionSave_series_nfo = QtGui.QAction(MainWindow)
        self.actionSave_series_nfo.setObjectName("actionSave_series_nfo")
        self.actionSave_episode_artwork = QtGui.QAction(MainWindow)
        self.actionSave_episode_artwork.setObjectName("actionSave_episode_artwork")
        self.actionSave_episode_nfo = QtGui.QAction(MainWindow)
        self.actionSave_episode_nfo.setObjectName("actionSave_episode_nfo")
        self.actionSave_series_both = QtGui.QAction(MainWindow)
        self.actionSave_series_both.setObjectName("actionSave_series_both")
        self.actionSave_episode_both = QtGui.QAction(MainWindow)
        self.actionSave_episode_both.setObjectName("actionSave_episode_both")
        self.menuTools.addAction(self.actionScan_Files)
        self.menuTools.addAction(self.actionEdit_Preferences)
        self.menuTools.addAction(self.actionClear_Cache)
        self.menuSeries.addAction(self.actionSave_series_artwork)
        self.menuSeries.addAction(self.actionSave_series_nfo)
        self.menuSeries.addAction(self.actionSave_series_both)
        self.menuEpisode.addAction(self.actionSave_episode_artwork)
        self.menuEpisode.addAction(self.actionSave_episode_nfo)
        self.menuEpisode.addAction(self.actionSave_episode_both)
        self.menuSave.addAction(self.actionSave_all)
        self.menuSave.addAction(self.menuSeries.menuAction())
        self.menuSave.addAction(self.menuEpisode.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_tv_info.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_series_name.setText(QtGui.QApplication.translate("MainWindow", "Series Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_overview.setText(QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_network.setText(QtGui.QApplication.translate("MainWindow", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.label_airtime.setText(QtGui.QApplication.translate("MainWindow", "Airtime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_runtime.setText(QtGui.QApplication.translate("MainWindow", "Runtime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tvdb_series_id.setText(QtGui.QApplication.translate("MainWindow", "thetvdb.com ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_actors.setText(QtGui.QApplication.translate("MainWindow", "Actors", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save_series_changes.setText(QtGui.QApplication.translate("MainWindow", "Apply Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_revert_series_changes.setText(QtGui.QApplication.translate("MainWindow", "Revert Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_series_banner.setText(QtGui.QApplication.translate("MainWindow", "No series poster selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_banner_wide.setText(QtGui.QApplication.translate("MainWindow", "No series wide banner selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_series_poster.setText(QtGui.QApplication.translate("MainWindow", "Select New Poster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_series_wide_banner.setText(QtGui.QApplication.translate("MainWindow", "Select New Wide Banner", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tv_info.setTabText(self.tabWidget_tv_info.indexOf(self.tab_series_info), QtGui.QApplication.translate("MainWindow", "Series Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_season_poster.setText(QtGui.QApplication.translate("MainWindow", "No season poster selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_season_banner_wide.setText(QtGui.QApplication.translate("MainWindow", "No season wide banner selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_season_poster.setText(QtGui.QApplication.translate("MainWindow", "Select New Poster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_season_wide.setText(QtGui.QApplication.translate("MainWindow", "Select New Wide Banner", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tv_info.setTabText(self.tabWidget_tv_info.indexOf(self.tab_season_info), QtGui.QApplication.translate("MainWindow", "Season Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_episode_name.setText(QtGui.QApplication.translate("MainWindow", "Episode Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_plot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_airdate.setText(QtGui.QApplication.translate("MainWindow", "Original Airdate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tvdb_id.setText(QtGui.QApplication.translate("MainWindow", "thetvdb.com ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tvdb_rating.setText(QtGui.QApplication.translate("MainWindow", "thetvdb.com Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.label_writers.setText(QtGui.QApplication.translate("MainWindow", "Writer(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_director.setText(QtGui.QApplication.translate("MainWindow", "Director(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_guests.setText(QtGui.QApplication.translate("MainWindow", "Guest Stars", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save_episode_changes.setText(QtGui.QApplication.translate("MainWindow", "Apply Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_revert_episode_changes.setText(QtGui.QApplication.translate("MainWindow", "Revert Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_episode_thumb.setText(QtGui.QApplication.translate("MainWindow", "No episode thumb selected", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tv_info.setTabText(self.tabWidget_tv_info.indexOf(self.tab_episode_info), QtGui.QApplication.translate("MainWindow", "Episode Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_tv), QtGui.QApplication.translate("MainWindow", "TV Shows", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_movies), QtGui.QApplication.translate("MainWindow", "Movies", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSeries.setTitle(QtGui.QApplication.translate("MainWindow", "Series", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEpisode.setTitle(QtGui.QApplication.translate("MainWindow", "Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_Files.setText(QtGui.QApplication.translate("MainWindow", "Scan Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Preferences.setText(QtGui.QApplication.translate("MainWindow", "Edit Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cache.setText(QtGui.QApplication.translate("MainWindow", "Clear Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Series_Artwork.setText(QtGui.QApplication.translate("MainWindow", "Save Series Artwork", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Series_nfo_Files.setText(QtGui.QApplication.translate("MainWindow", "Save Series .nfo Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelected_Series_nfo_Files.setText(QtGui.QApplication.translate("MainWindow", "Selected Series .nfo Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelected_Series_Artwork.setText(QtGui.QApplication.translate("MainWindow", "Selected Series Artwork", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_all.setText(QtGui.QApplication.translate("MainWindow", "All (Artwork and .nfo)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_series_artwork.setText(QtGui.QApplication.translate("MainWindow", "Artwork", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_series_nfo.setText(QtGui.QApplication.translate("MainWindow", ".nfo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_episode_artwork.setText(QtGui.QApplication.translate("MainWindow", "Artwork", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_episode_nfo.setText(QtGui.QApplication.translate("MainWindow", ".nfo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_series_both.setText(QtGui.QApplication.translate("MainWindow", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_episode_both.setText(QtGui.QApplication.translate("MainWindow", "Both", None, QtGui.QApplication.UnicodeUTF8))

