# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sun Oct 30 10:31:28 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1394, 996)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget_main = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_main.setObjectName(_fromUtf8("tabWidget_main"))
        self.tab_tv = QtGui.QWidget()
        self.tab_tv.setObjectName(_fromUtf8("tab_tv"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_tv)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listView_shows = QtGui.QListView(self.tab_tv)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_shows.sizePolicy().hasHeightForWidth())
        self.listView_shows.setSizePolicy(sizePolicy)
        self.listView_shows.setMinimumSize(QtCore.QSize(300, 0))
        self.listView_shows.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listView_shows.setObjectName(_fromUtf8("listView_shows"))
        self.horizontalLayout.addWidget(self.listView_shows)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_tv_info = QtGui.QTabWidget(self.tab_tv)
        self.tabWidget_tv_info.setObjectName(_fromUtf8("tabWidget_tv_info"))
        self.tab_series_info = QtGui.QWidget()
        self.tab_series_info.setObjectName(_fromUtf8("tab_series_info"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_series_info)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lineEdit_series_name = QtGui.QLineEdit(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_series_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_series_name.setSizePolicy(sizePolicy)
        self.lineEdit_series_name.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_series_name.setObjectName(_fromUtf8("lineEdit_series_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lineEdit_series_name)
        self.label_series_name = QtGui.QLabel(self.tab_series_info)
        self.label_series_name.setText(QtGui.QApplication.translate("MainWindow", "Series Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_series_name.setObjectName(_fromUtf8("label_series_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_series_name)
        self.plainTextEdit_overview = QtGui.QPlainTextEdit(self.tab_series_info)
        self.plainTextEdit_overview.setMinimumSize(QtCore.QSize(300, 50))
        self.plainTextEdit_overview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit_overview.setObjectName(_fromUtf8("plainTextEdit_overview"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.plainTextEdit_overview)
        self.label_overview = QtGui.QLabel(self.tab_series_info)
        self.label_overview.setText(QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_overview.setObjectName(_fromUtf8("label_overview"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_overview)
        self.lineEdit_network = QtGui.QLineEdit(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_network.sizePolicy().hasHeightForWidth())
        self.lineEdit_network.setSizePolicy(sizePolicy)
        self.lineEdit_network.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_network.setObjectName(_fromUtf8("lineEdit_network"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEdit_network)
        self.label_network = QtGui.QLabel(self.tab_series_info)
        self.label_network.setText(QtGui.QApplication.translate("MainWindow", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.label_network.setObjectName(_fromUtf8("label_network"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_network)
        self.lineEdit_airtime = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_airtime.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_airtime.setObjectName(_fromUtf8("lineEdit_airtime"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEdit_airtime)
        self.label_airtime = QtGui.QLabel(self.tab_series_info)
        self.label_airtime.setText(QtGui.QApplication.translate("MainWindow", "Airtime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_airtime.setObjectName(_fromUtf8("label_airtime"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_airtime)
        self.lineEdit_runtime = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_runtime.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_runtime.setObjectName(_fromUtf8("lineEdit_runtime"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lineEdit_runtime)
        self.label_runtime = QtGui.QLabel(self.tab_series_info)
        self.label_runtime.setText(QtGui.QApplication.translate("MainWindow", "Runtime", None, QtGui.QApplication.UnicodeUTF8))
        self.label_runtime.setObjectName(_fromUtf8("label_runtime"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_runtime)
        self.lineEdit_status = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_status.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_status.setObjectName(_fromUtf8("lineEdit_status"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lineEdit_status)
        self.label_status = QtGui.QLabel(self.tab_series_info)
        self.label_status.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_status)
        self.lineEdit_tvdb_series_id = QtGui.QLineEdit(self.tab_series_info)
        self.lineEdit_tvdb_series_id.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_tvdb_series_id.setObjectName(_fromUtf8("lineEdit_tvdb_series_id"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lineEdit_tvdb_series_id)
        self.label_tvdb_series_id = QtGui.QLabel(self.tab_series_info)
        self.label_tvdb_series_id.setText(QtGui.QApplication.translate("MainWindow", "thetvdb.com ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tvdb_series_id.setObjectName(_fromUtf8("label_tvdb_series_id"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_tvdb_series_id)
        self.combo_actors = QtGui.QComboBox(self.tab_series_info)
        self.combo_actors.setMinimumSize(QtCore.QSize(300, 0))
        self.combo_actors.setObjectName(_fromUtf8("combo_actors"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.combo_actors)
        self.label_actors = QtGui.QLabel(self.tab_series_info)
        self.label_actors.setText(QtGui.QApplication.translate("MainWindow", "Actors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_actors.setObjectName(_fromUtf8("label_actors"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_actors)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_save_series_changes = QtGui.QPushButton(self.tab_series_info)
        self.pushButton_save_series_changes.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_save_series_changes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_save_series_changes.setText(QtGui.QApplication.translate("MainWindow", "Apply Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save_series_changes.setObjectName(_fromUtf8("pushButton_save_series_changes"))
        self.gridLayout_4.addWidget(self.pushButton_save_series_changes, 0, 0, 1, 1)
        self.pushButton_new_series_poster = QtGui.QPushButton(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new_series_poster.sizePolicy().hasHeightForWidth())
        self.pushButton_new_series_poster.setSizePolicy(sizePolicy)
        self.pushButton_new_series_poster.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_series_poster.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_series_poster.setText(QtGui.QApplication.translate("MainWindow", "Select New Poster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_series_poster.setObjectName(_fromUtf8("pushButton_new_series_poster"))
        self.gridLayout_4.addWidget(self.pushButton_new_series_poster, 0, 1, 1, 1)
        self.pushButton_revert_series_changes = QtGui.QPushButton(self.tab_series_info)
        self.pushButton_revert_series_changes.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_revert_series_changes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_revert_series_changes.setText(QtGui.QApplication.translate("MainWindow", "Revert Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_revert_series_changes.setObjectName(_fromUtf8("pushButton_revert_series_changes"))
        self.gridLayout_4.addWidget(self.pushButton_revert_series_changes, 1, 0, 1, 1)
        self.pushButton_new_series_wide_banner = QtGui.QPushButton(self.tab_series_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new_series_wide_banner.sizePolicy().hasHeightForWidth())
        self.pushButton_new_series_wide_banner.setSizePolicy(sizePolicy)
        self.pushButton_new_series_wide_banner.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_series_wide_banner.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_series_wide_banner.setText(QtGui.QApplication.translate("MainWindow", "Select New Wide Banner", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_series_wide_banner.setObjectName(_fromUtf8("pushButton_new_series_wide_banner"))
        self.gridLayout_4.addWidget(self.pushButton_new_series_wide_banner, 1, 1, 1, 1)
        self.formLayout.setLayout(8, QtGui.QFormLayout.LabelRole, self.gridLayout_4)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.label_series_banner = QtGui.QLabel(self.tab_series_info)
        self.label_series_banner.setMinimumSize(QtCore.QSize(300, 450))
        self.label_series_banner.setText(QtGui.QApplication.translate("MainWindow", "No Series Poster Available", None, QtGui.QApplication.UnicodeUTF8))
        self.label_series_banner.setObjectName(_fromUtf8("label_series_banner"))
        self.horizontalLayout_2.addWidget(self.label_series_banner)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_banner_wide = QtGui.QLabel(self.tab_series_info)
        self.label_banner_wide.setMinimumSize(QtCore.QSize(760, 140))
        self.label_banner_wide.setText(QtGui.QApplication.translate("MainWindow", "No Wide Banner Available", None, QtGui.QApplication.UnicodeUTF8))
        self.label_banner_wide.setObjectName(_fromUtf8("label_banner_wide"))
        self.verticalLayout_2.addWidget(self.label_banner_wide)
        self.tabWidget_tv_info.addTab(self.tab_series_info, _fromUtf8(""))
        self.tab_season_info = QtGui.QWidget()
        self.tab_season_info.setObjectName(_fromUtf8("tab_season_info"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_season_info)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.listView_season_episode_full = QtGui.QListView(self.tab_season_info)
        self.listView_season_episode_full.setObjectName(_fromUtf8("listView_season_episode_full"))
        self.horizontalLayout_4.addWidget(self.listView_season_episode_full)
        self.label_season_poster = QtGui.QLabel(self.tab_season_info)
        self.label_season_poster.setMinimumSize(QtCore.QSize(300, 450))
        self.label_season_poster.setText(QtGui.QApplication.translate("MainWindow", "No Season Poster Available", None, QtGui.QApplication.UnicodeUTF8))
        self.label_season_poster.setObjectName(_fromUtf8("label_season_poster"))
        self.horizontalLayout_4.addWidget(self.label_season_poster)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_season_banner_wide = QtGui.QLabel(self.tab_season_info)
        self.label_season_banner_wide.setMinimumSize(QtCore.QSize(760, 140))
        self.label_season_banner_wide.setText(QtGui.QApplication.translate("MainWindow", "No Season Wide Banner Available", None, QtGui.QApplication.UnicodeUTF8))
        self.label_season_banner_wide.setObjectName(_fromUtf8("label_season_banner_wide"))
        self.horizontalLayout_5.addWidget(self.label_season_banner_wide)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_new_season_poster = QtGui.QPushButton(self.tab_season_info)
        self.pushButton_new_season_poster.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_season_poster.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_season_poster.setText(QtGui.QApplication.translate("MainWindow", "Select New Poster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_season_poster.setObjectName(_fromUtf8("pushButton_new_season_poster"))
        self.verticalLayout_4.addWidget(self.pushButton_new_season_poster)
        self.pushButton_new_season_wide = QtGui.QPushButton(self.tab_season_info)
        self.pushButton_new_season_wide.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_new_season_wide.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_new_season_wide.setText(QtGui.QApplication.translate("MainWindow", "Select New Wide Banner", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_season_wide.setObjectName(_fromUtf8("pushButton_new_season_wide"))
        self.verticalLayout_4.addWidget(self.pushButton_new_season_wide)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget_tv_info.addTab(self.tab_season_info, _fromUtf8(""))
        self.tab_episode_info = QtGui.QWidget()
        self.tab_episode_info.setObjectName(_fromUtf8("tab_episode_info"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_episode_info)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.line_episode_name = QtGui.QLineEdit(self.tab_episode_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_episode_name.sizePolicy().hasHeightForWidth())
        self.line_episode_name.setSizePolicy(sizePolicy)
        self.line_episode_name.setMinimumSize(QtCore.QSize(400, 0))
        self.line_episode_name.setObjectName(_fromUtf8("line_episode_name"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.line_episode_name)
        self.label_episode_name = QtGui.QLabel(self.tab_episode_info)
        self.label_episode_name.setText(QtGui.QApplication.translate("MainWindow", "Episode Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_episode_name.setObjectName(_fromUtf8("label_episode_name"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_episode_name)
        self.text_episode_plot = QtGui.QPlainTextEdit(self.tab_episode_info)
        self.text_episode_plot.setMinimumSize(QtCore.QSize(400, 100))
        self.text_episode_plot.setObjectName(_fromUtf8("text_episode_plot"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.text_episode_plot)
        self.label_plot = QtGui.QLabel(self.tab_episode_info)
        self.label_plot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_plot.setObjectName(_fromUtf8("label_plot"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_plot)
        self.line_airdate = QtGui.QLineEdit(self.tab_episode_info)
        self.line_airdate.setMinimumSize(QtCore.QSize(400, 0))
        self.line_airdate.setObjectName(_fromUtf8("line_airdate"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.line_airdate)
        self.label_airdate = QtGui.QLabel(self.tab_episode_info)
        self.label_airdate.setText(QtGui.QApplication.translate("MainWindow", "Original Airdate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_airdate.setObjectName(_fromUtf8("label_airdate"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_airdate)
        self.line_tvdb_id = QtGui.QLineEdit(self.tab_episode_info)
        self.line_tvdb_id.setMinimumSize(QtCore.QSize(400, 0))
        self.line_tvdb_id.setObjectName(_fromUtf8("line_tvdb_id"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.line_tvdb_id)
        self.label_tvdb_id = QtGui.QLabel(self.tab_episode_info)
        self.label_tvdb_id.setText(QtGui.QApplication.translate("MainWindow", "thetvdb.com ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tvdb_id.setObjectName(_fromUtf8("label_tvdb_id"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_tvdb_id)
        self.line_tvdb_rating = QtGui.QLineEdit(self.tab_episode_info)
        self.line_tvdb_rating.setMinimumSize(QtCore.QSize(400, 0))
        self.line_tvdb_rating.setObjectName(_fromUtf8("line_tvdb_rating"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.line_tvdb_rating)
        self.label_tvdb_rating = QtGui.QLabel(self.tab_episode_info)
        self.label_tvdb_rating.setText(QtGui.QApplication.translate("MainWindow", "thetvdb.com Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tvdb_rating.setObjectName(_fromUtf8("label_tvdb_rating"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_tvdb_rating)
        self.combo_writers = QtGui.QComboBox(self.tab_episode_info)
        self.combo_writers.setMinimumSize(QtCore.QSize(400, 0))
        self.combo_writers.setObjectName(_fromUtf8("combo_writers"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.combo_writers)
        self.label_writers = QtGui.QLabel(self.tab_episode_info)
        self.label_writers.setText(QtGui.QApplication.translate("MainWindow", "Writer(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_writers.setObjectName(_fromUtf8("label_writers"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_writers)
        self.combo_directors = QtGui.QComboBox(self.tab_episode_info)
        self.combo_directors.setMinimumSize(QtCore.QSize(400, 0))
        self.combo_directors.setObjectName(_fromUtf8("combo_directors"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.combo_directors)
        self.label_director = QtGui.QLabel(self.tab_episode_info)
        self.label_director.setText(QtGui.QApplication.translate("MainWindow", "Director(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_director.setObjectName(_fromUtf8("label_director"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_director)
        self.combo_guests = QtGui.QComboBox(self.tab_episode_info)
        self.combo_guests.setMinimumSize(QtCore.QSize(400, 0))
        self.combo_guests.setObjectName(_fromUtf8("combo_guests"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.combo_guests)
        self.label_guests = QtGui.QLabel(self.tab_episode_info)
        self.label_guests.setText(QtGui.QApplication.translate("MainWindow", "Guest Stars", None, QtGui.QApplication.UnicodeUTF8))
        self.label_guests.setObjectName(_fromUtf8("label_guests"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.label_guests)
        self.pushButton_save_episode_changes = QtGui.QPushButton(self.tab_episode_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_episode_changes.sizePolicy().hasHeightForWidth())
        self.pushButton_save_episode_changes.setSizePolicy(sizePolicy)
        self.pushButton_save_episode_changes.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_save_episode_changes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_save_episode_changes.setText(QtGui.QApplication.translate("MainWindow", "Apply Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save_episode_changes.setObjectName(_fromUtf8("pushButton_save_episode_changes"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.pushButton_save_episode_changes)
        self.pushButton_revert_episode_changes = QtGui.QPushButton(self.tab_episode_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_revert_episode_changes.sizePolicy().hasHeightForWidth())
        self.pushButton_revert_episode_changes.setSizePolicy(sizePolicy)
        self.pushButton_revert_episode_changes.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_revert_episode_changes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_revert_episode_changes.setText(QtGui.QApplication.translate("MainWindow", "Revert Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_revert_episode_changes.setObjectName(_fromUtf8("pushButton_revert_episode_changes"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.pushButton_revert_episode_changes)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_episode_thumb = QtGui.QLabel(self.tab_episode_info)
        self.label_episode_thumb.setMinimumSize(QtCore.QSize(400, 225))
        self.label_episode_thumb.setText(QtGui.QApplication.translate("MainWindow", "No Episode Thumb Available", None, QtGui.QApplication.UnicodeUTF8))
        self.label_episode_thumb.setObjectName(_fromUtf8("label_episode_thumb"))
        self.verticalLayout_3.addWidget(self.label_episode_thumb)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabWidget_tv_info.addTab(self.tab_episode_info, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_tv_info)
        self.columnView_season_episode = QtGui.QColumnView(self.tab_tv)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columnView_season_episode.sizePolicy().hasHeightForWidth())
        self.columnView_season_episode.setSizePolicy(sizePolicy)
        self.columnView_season_episode.setMinimumSize(QtCore.QSize(0, 200))
        self.columnView_season_episode.setMaximumSize(QtCore.QSize(16777215, 400))
        self.columnView_season_episode.setObjectName(_fromUtf8("columnView_season_episode"))
        self.verticalLayout.addWidget(self.columnView_season_episode)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget_main.addTab(self.tab_tv, _fromUtf8(""))
        self.tab_movies = QtGui.QWidget()
        self.tab_movies.setObjectName(_fromUtf8("tab_movies"))
        self.tabWidget_main.addTab(self.tab_movies, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1394, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionScan_Files = QtGui.QAction(MainWindow)
        self.actionScan_Files.setText(QtGui.QApplication.translate("MainWindow", "Scan Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_Files.setObjectName(_fromUtf8("actionScan_Files"))
        self.actionEdit_Preferences = QtGui.QAction(MainWindow)
        self.actionEdit_Preferences.setText(QtGui.QApplication.translate("MainWindow", "Edit Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Preferences.setObjectName(_fromUtf8("actionEdit_Preferences"))
        self.actionClear_Cache = QtGui.QAction(MainWindow)
        self.actionClear_Cache.setText(QtGui.QApplication.translate("MainWindow", "Clear Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cache.setObjectName(_fromUtf8("actionClear_Cache"))
        self.menuTools.addAction(self.actionScan_Files)
        self.menuTools.addAction(self.actionEdit_Preferences)
        self.menuTools.addAction(self.actionClear_Cache)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_tv_info.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget_tv_info.setTabText(self.tabWidget_tv_info.indexOf(self.tab_series_info), QtGui.QApplication.translate("MainWindow", "Series Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tv_info.setTabText(self.tabWidget_tv_info.indexOf(self.tab_season_info), QtGui.QApplication.translate("MainWindow", "Season Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_tv_info.setTabText(self.tabWidget_tv_info.indexOf(self.tab_episode_info), QtGui.QApplication.translate("MainWindow", "Episode Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_tv), QtGui.QApplication.translate("MainWindow", "TV Shows", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_movies), QtGui.QApplication.translate("MainWindow", "Movies", None, QtGui.QApplication.UnicodeUTF8))

